/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_CLOCK_PROGRAM_PB_H_INCLUDED
#define PB_CLOCK_PROGRAM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ClockProgram {
    int32_t hour_offset;
    int32_t fade_animation_del;
    bool en_hourly_messages;
    bool en_blink_heart;
    bool en_display;
} ClockProgram;


/* Initializer values for message structs */
#define ClockProgram_init_default                {0, 0, 0, 0, 0}
#define ClockProgram_init_zero                   {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ClockProgram_hour_offset_tag             1
#define ClockProgram_fade_animation_del_tag      2
#define ClockProgram_en_hourly_messages_tag      3
#define ClockProgram_en_blink_heart_tag          4
#define ClockProgram_en_display_tag              5

/* Struct field encoding specification for nanopb */
#define ClockProgram_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    hour_offset,       1) \
X(a, STATIC,   SINGULAR, INT32,    fade_animation_del,   2) \
X(a, STATIC,   SINGULAR, BOOL,     en_hourly_messages,   3) \
X(a, STATIC,   SINGULAR, BOOL,     en_blink_heart,    4) \
X(a, STATIC,   SINGULAR, BOOL,     en_display,        5)
#define ClockProgram_CALLBACK NULL
#define ClockProgram_DEFAULT NULL

extern const pb_msgdesc_t ClockProgram_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ClockProgram_fields &ClockProgram_msg

/* Maximum encoded size of messages (where known) */
#define ClockProgram_size                        28

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
