/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_MESSAGE_RETURN_STATUS_PB_H_INCLUDED
#define PB_MESSAGE_RETURN_STATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _ReturnMessage_MessageStatus {
    ReturnMessage_MessageStatus_CMD_ACCEPTED = 0,
    ReturnMessage_MessageStatus_CMD_FAILED = 1,
    ReturnMessage_MessageStatus_CMD_UNRECOGNIZED = 2,
    ReturnMessage_MessageStatus_CMD_NOT_ON_DEVICE = 3,
    ReturnMessage_MessageStatus_NO_CMD = 4
} ReturnMessage_MessageStatus;

/* Struct definitions */
typedef struct _ReturnMessage {
    ReturnMessage_MessageStatus message_status;
} ReturnMessage;


/* Helper constants for enums */
#define _ReturnMessage_MessageStatus_MIN ReturnMessage_MessageStatus_CMD_ACCEPTED
#define _ReturnMessage_MessageStatus_MAX ReturnMessage_MessageStatus_NO_CMD
#define _ReturnMessage_MessageStatus_ARRAYSIZE ((ReturnMessage_MessageStatus)(ReturnMessage_MessageStatus_NO_CMD+1))


/* Initializer values for message structs */
#define ReturnMessage_init_default               {_ReturnMessage_MessageStatus_MIN}
#define ReturnMessage_init_zero                  {_ReturnMessage_MessageStatus_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define ReturnMessage_message_status_tag         1

/* Struct field encoding specification for nanopb */
#define ReturnMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    message_status,    1)
#define ReturnMessage_CALLBACK NULL
#define ReturnMessage_DEFAULT NULL

extern const pb_msgdesc_t ReturnMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ReturnMessage_fields &ReturnMessage_msg

/* Maximum encoded size of messages (where known) */
#define ReturnMessage_size                       2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
