/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "message_return_status.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ReturnMessage, ReturnMessage, AUTO)




